<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-OT2UM6DD" failures="1" tests="2" name="Default test(failed)(failed)" time="0.061" errors="0" timestamp="2022-09-14T12:25:02 IST">
  <testcase classname="org.sdet40.practise.TestNGRetryFailDemo" name="test2" time="0.01"/>
  <testcase classname="org.sdet40.practise.TestNGRetryFailDemo" name="test3" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.sdet40.practise.TestNGRetryFailDemo.test3(TestNGRetryFailDemo.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="org.sdet40.practise.TestNGRetryFailDemo" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed)(failed) -->
